
## Developer Information (Required)
* Name: Hantang
* Email Address: hantang2@illinois.edu



## Data Description (Required)
(For example,

* The `babynames` data is from the **babynames** package. It contains the all baby names with at least 5 uses from 1880 to 2017. There are five variables: year, sex, name, n, and prop.
* The original data for female life expectancy was sourced from https://data.worldbank.org/indicator/SP.DYN.LE00.FE.IN. Life expectancy at birth indicates the number of years a newborn infant would live if prevailing patterns of mortality at the time of its birth were to stay the same throughout its life.
After data wrangling, the "Female Life Expectancy.csv" dataset contains 6 variables: CountryName, CountryCode, Year, LifeExp, Region, and IncomeGroup. Additionally, the "Country Name and Code.csv" dataset contains two columns: CountryName and CountryCode.

)


The data is from the UCI Machine Learning Website **Wine Quality Data Set**. The dataset contain two CSV files, one for red wine and one for white wine, containing key features, like physicochemical properties and quality ratings for each type of wine.

- **Red Wine Quality Data:**
  - **Source:** [UCI Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/Wine+Quality)
  
  - **Description:** This dataset includes various physicochemical elementsfor red wine samples from the north part of Portugal. Goal is to model wine quality based on physicochemical tests.
  
  - **Variables:** 12 variables including fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, and quality score (0-10).

- **White Wine Quality Data:**
  - **Source:** [UCI Wine Quality Data Set] (https://archive.ics.uci.edu/ml/datasets/Wine+Quality)
  
  - **Description:** This dataset has variables of  physicochemical for white wine samples from the same north of Portugal. Same goal based on physicochemical tests is to model wine quality for this analysis.
  - **Variables:**  same 12 variables as Red Wine. 

Both datasets are combined in the analysis to facilitate comparisons and broader insights.



## Describe the App -- Briefly describe what the app does and its potential uses (Required)

* The Wine Quality Analysis app allows users to explore the quality of red and white wines,which also allows user to analyze based on various physicochemical properties. Users can select the wine type, filter the elements base on what is needed, and analyze the relationships between two variables on the dot plot.

* **Potential Uses:**
  - **Educational Tool:** The app can be used by students and researchers to understand data analysis, and machine learning concepts on the wine qualities.
  - **Wine Industry:** Winemakers can use the app to explore factors affecting wine quality and start off an early optimize production processes.
  - **Research:** Researchers can make the app to study the correlation between physicochemical properties and wine quality base on the key features and dots on the plot.


## Reference (Required)

* [UCI Machine Learning Repository - Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/Wine+Quality)




## Challenges Faced (Optional)

* Cleaning the missing data to ensure it is properly formatted for analysis and let Rstudio to understand.
* Implementing reactive elements in Shiny to dynamically update plots based on user inputs or adjust user filter.


## Solutions Implemented (Optional)

* Use the `dplyr` package for data   cleaning to ensure datasets were correctly merged and able to filtered by Rstudio.
* Utilized Shiny's reactive programming model to create a responsive interface for user selections.



## Additional Notes (Optional)

* Future improvements could include more statistical analysis and machine learning models to predict wine quality, which not just dot plot.
* Consider incorporating interactive elements such as more filtering options and research need visualization types.

